[build]
  functions = "netlify/functions"
  command = "echo 'No build needed'"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200

[build.environment]
  NODE_VERSION = "18"

